//! rurix.lock 精确解析图序列化(RXS-0092)。
//!
//! lock 是解析图(RXS-0091)的确定性序列化:`[[package]]` 按 name 排序、数组字段
//! 元素排序,逐字节稳定。`--locked` 下重解析图 ≠ 入库 lock → [`PkgError::LockMismatch`]
//! (RX7007),不静默重写。

use crate::error::{PkgError, PkgResult};
use crate::manifest::Version;
use crate::resolve::ResolveGraph;
use crate::toml::{self, Value};

pub const LOCK_VERSION: i64 = 1;

/// lock 中的一个包项(source 为 RXS-0090 稳定编码字符串)。
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockPackage {
    pub name: String,
    pub version: String,
    pub source: String,
    pub content_sha256: String,
    pub features: Vec<String>,
    pub deps: Vec<String>,
}

/// rurix.lock 文档(确定性)。
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lock {
    pub root: String,
    pub packages: Vec<LockPackage>,
}

impl Lock {
    /// 由解析图构造 lock(确定性:包按 name 排序,数组排序)。
    pub fn from_graph(graph: &ResolveGraph) -> Lock {
        let mut packages: Vec<LockPackage> = graph
            .nodes
            .values()
            .map(|p| {
                let mut features = p.features.clone();
                features.sort();
                let mut deps = p.deps.clone();
                deps.sort();
                LockPackage {
                    name: p.name.clone(),
                    version: p.version.to_string(),
                    source: p.source.locator(),
                    content_sha256: p.content_sha256.clone(),
                    features,
                    deps,
                }
            })
            .collect();
        packages.sort_by(|a, b| a.name.cmp(&b.name));
        Lock {
            root: graph.root.clone(),
            packages,
        }
    }

    /// 确定性序列化为 rurix.lock 文本(逐字节稳定,RXS-0092)。
    pub fn serialize(&self) -> String {
        let mut s = String::new();
        s.push_str("# rurix.lock — generated by `rx vendor`; do not edit by hand.\n");
        s.push_str(&format!("lock_version = {LOCK_VERSION}\n"));
        s.push_str(&format!("root = {}\n", quote(&self.root)));
        for pkg in &self.packages {
            s.push('\n');
            s.push_str("[[package]]\n");
            s.push_str(&format!("name = {}\n", quote(&pkg.name)));
            s.push_str(&format!("version = {}\n", quote(&pkg.version)));
            s.push_str(&format!("source = {}\n", quote(&pkg.source)));
            s.push_str(&format!(
                "content_sha256 = {}\n",
                quote(&pkg.content_sha256)
            ));
            s.push_str(&format!("features = {}\n", str_array(&pkg.features)));
            s.push_str(&format!("deps = {}\n", str_array(&pkg.deps)));
        }
        s
    }

    /// 解析 rurix.lock 文本(RXS-0092)。结构性损坏 → RX7007。
    pub fn parse(text: &str) -> PkgResult<Lock> {
        let root_tbl = toml::parse(text).map_err(PkgError::LockMismatch)?;
        let lock_version = root_tbl
            .get("lock_version")
            .and_then(Value::as_integer)
            .ok_or_else(|| PkgError::LockMismatch("缺 lock_version".to_owned()))?;
        if lock_version != LOCK_VERSION {
            return Err(PkgError::LockMismatch(format!(
                "lock_version {lock_version} 不受支持(期待 {LOCK_VERSION})"
            )));
        }
        let root = root_tbl
            .get("root")
            .and_then(Value::as_str)
            .ok_or_else(|| PkgError::LockMismatch("缺 root".to_owned()))?
            .to_owned();
        let mut packages = Vec::new();
        if let Some(arr) = root_tbl.get("package").and_then(Value::as_array) {
            for item in arr {
                let t = item
                    .as_table()
                    .ok_or_else(|| PkgError::LockMismatch("[[package]] 非表".to_owned()))?;
                let get = |k: &str| -> PkgResult<String> {
                    t.get(k)
                        .and_then(Value::as_str)
                        .map(str::to_owned)
                        .ok_or_else(|| PkgError::LockMismatch(format!("[[package]] 缺 {k}")))
                };
                let version = get("version")?;
                Version::parse(&version).map_err(PkgError::LockMismatch)?;
                let arr_field = |k: &str| -> PkgResult<Vec<String>> {
                    match t.get(k) {
                        Some(v) => v.as_str_array().map_err(PkgError::LockMismatch),
                        None => Ok(Vec::new()),
                    }
                };
                packages.push(LockPackage {
                    name: get("name")?,
                    version,
                    source: get("source")?,
                    content_sha256: get("content_sha256")?,
                    features: arr_field("features")?,
                    deps: arr_field("deps")?,
                });
            }
        }
        packages.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(Lock { root, packages })
    }

    /// `--locked` 一致性核对(RXS-0092):本 lock 须与由当前清单重解析得到的图
    /// 完全一致,否则 RX7007。
    pub fn check_consistent(&self, graph: &ResolveGraph) -> PkgResult<()> {
        let fresh = Lock::from_graph(graph);
        if *self != fresh {
            return Err(PkgError::LockMismatch(
                "入库 rurix.lock 与当前清单重解析图不一致(--locked 不重写;请重新 `rx vendor`)"
                    .to_owned(),
            ));
        }
        Ok(())
    }
}

fn quote(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

fn str_array(items: &[String]) -> String {
    if items.is_empty() {
        return "[]".to_owned();
    }
    let inner: Vec<String> = items.iter().map(|s| quote(s)).collect();
    format!("[{}]", inner.join(", "))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Source;
    use crate::resolve::{ResolveGraph, ResolvedPackage};
    use std::collections::BTreeMap;

    fn sample_graph() -> ResolveGraph {
        let mut nodes = BTreeMap::new();
        nodes.insert(
            "app".to_owned(),
            ResolvedPackage {
                name: "app".to_owned(),
                version: Version::parse("0.1.0").unwrap(),
                source: Source::Path(".".to_owned()),
                content_sha256: "a".repeat(64),
                features: vec!["default".to_owned()],
                deps: vec!["foo".to_owned()],
            },
        );
        nodes.insert(
            "foo".to_owned(),
            ResolvedPackage {
                name: "foo".to_owned(),
                version: Version::parse("0.2.0").unwrap(),
                source: Source::Path("../foo".to_owned()),
                content_sha256: "f".repeat(64),
                features: vec![],
                deps: vec![],
            },
        );
        ResolveGraph {
            root: "app".to_owned(),
            nodes,
        }
    }

    //@ spec: RXS-0092
    #[test]
    fn serialize_parse_round_trip() {
        let g = sample_graph();
        let lock = Lock::from_graph(&g);
        let text = lock.serialize();
        let parsed = Lock::parse(&text).unwrap();
        assert_eq!(lock, parsed);
        // 二次序列化逐字节稳定。
        assert_eq!(text, parsed.serialize());
    }

    //@ spec: RXS-0092
    #[test]
    fn locked_consistency_detects_mismatch() {
        let g = sample_graph();
        let lock = Lock::from_graph(&g);
        // 一致 → Ok。
        assert!(lock.check_consistent(&g).is_ok());
        // 篡改图(改 content_sha256)→ RX7007。
        let mut g2 = g.clone();
        g2.nodes.get_mut("foo").unwrap().content_sha256 = "0".repeat(64);
        let err = lock.check_consistent(&g2).unwrap_err();
        assert_eq!(err.code(), "RX7007");
    }
}
