#!/usr/bin/env python3
"""Run the GRX-003 Godot load smoke for present/missing DLL cases."""

from __future__ import annotations

import json
import pathlib
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
GODOT_CONSOLE_EXE = (
    ROOT / "external" / "godot-master" / "bin" / "godot.windows.template_debug.x86_64.console.exe"
)
PRESENT_DLL = ROOT / "target" / "debug" / "rurix_godot.dll"
PROJECT_DIR = ROOT / "target" / "grx" / "godot-load-smoke"
PROJECT_FILE = PROJECT_DIR / "project.godot"
MAIN_SCENE = PROJECT_DIR / "main.tscn"
MAIN_SCRIPT = PROJECT_DIR / "main.gd"
LOG_DIR = PROJECT_DIR / "logs"
SUMMARY_PATH = ROOT / "target" / "grx" / "godot_load_smoke_summary.json"
TIMEOUT_SECONDS = 90
REQUESTED_RENDERER = "d3d12"
REQUESTED_RENDERING_METHOD = "forward_plus"
MISSING_DLL = PROJECT_DIR / "missing" / "rurix_godot_missing.dll"
LEGACY_RUNTIME_DIR = GODOT_CONSOLE_EXE.parent
LEGACY_RUNTIME_FILES = (
    LEGACY_RUNTIME_DIR / "project.godot",
    LEGACY_RUNTIME_DIR / "main.tscn",
    LEGACY_RUNTIME_DIR / "main.gd",
)
LEGACY_MAIN_SCENE_FINGERPRINT = """\
[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://main.gd" id="1"]

[node name="Main" type="Node"]
script = ExtResource("1")
"""

SCENE_READY_MARKER = "GRXLoadSmoke: scene ready"
SCENE_QUIT_MARKER = "GRXLoadSmoke: quitting"
READY_MARKER = "RurixAccel: D3D12 Forward+ bridge session ready."
MISSING_DLL_MARKER = "RurixAccel: rurix_godot.dll not found; Godot fallback path remains active."
SESSION_UNAVAILABLE_MARKER = "RurixAccel: session unavailable rc="
SMOKE_CONTENT_MARKERS = (
    "Auto-generated by ci/godot_rurix_load_smoke.py",
    "GRXLoadSmoke",
)
SKIP_HINTS = (
    SESSION_UNAVAILABLE_MARKER,
    "D3D12",
    "DXGI",
    "adapter",
    "feature level",
    "rendering device",
    "rendering driver",
)


def combined_output(proc: subprocess.CompletedProcess[str]) -> str:
    parts = []
    if proc.stdout:
        parts.append(proc.stdout.rstrip())
    if proc.stderr:
        parts.append(proc.stderr.rstrip())
    return "\n".join(part for part in parts if part).strip()


def normalized_text(text: str) -> str:
    return text.replace("\r\n", "\n").strip()


def write_project(dll_path: pathlib.Path) -> None:
    PROJECT_DIR.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    project_text = f"""\
; Engine configuration file.
; Auto-generated by ci/godot_rurix_load_smoke.py

config_version=5

[application]

config/name="GRX Load Smoke"
run/main_scene="res://main.tscn"

[rendering]

rurix_accel/enabled=true
rurix_accel/require_forward_plus=true
rurix_accel/dll_path="{dll_path.as_posix()}"
"""
    scene_text = """\
[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://main.gd" id="1"]

[node name="GRXLoadSmokeRoot" type="Node"]
script = ExtResource("1")
"""
    script_text = """\
extends Node

func _ready() -> void:
    print("GRXLoadSmoke: scene ready")
    _quit_later()

func _quit_later() -> void:
    await get_tree().create_timer(1.0).timeout
    print("GRXLoadSmoke: quitting")
    get_tree().quit()
"""
    PROJECT_FILE.write_text(project_text, encoding="utf-8")
    MAIN_SCENE.write_text(scene_text, encoding="utf-8")
    MAIN_SCRIPT.write_text(script_text, encoding="utf-8")


def classify_legacy_runtime_file(
    legacy_file: pathlib.Path,
    content: str,
) -> tuple[bool, str]:
    if any(marker in content for marker in SMOKE_CONTENT_MARKERS):
        return True, "matched smoke content marker"
    if legacy_file.name.lower() == "main.tscn" and normalized_text(content) == normalized_text(
        LEGACY_MAIN_SCENE_FINGERPRINT
    ):
        return True, "matched exact legacy scene fingerprint"
    return False, "content did not match smoke markers or exact legacy scene fingerprint"


def cleanup_legacy_runtime_files() -> dict[str, object]:
    removed: list[str] = []
    skipped: dict[str, str] = {}
    for legacy_file in LEGACY_RUNTIME_FILES:
        if not legacy_file.exists():
            continue
        try:
            content = legacy_file.read_text(encoding="utf-8")
        except OSError:
            skipped[str(legacy_file)] = "failed to read legacy runtime file"
            continue
        should_remove, reason = classify_legacy_runtime_file(legacy_file, content)
        if not should_remove:
            skipped[str(legacy_file)] = reason
            continue
        try:
            legacy_file.unlink()
        except OSError:
            skipped[str(legacy_file)] = "failed to delete matched legacy runtime file"
            continue
        removed.append(str(legacy_file))
    return {
        "removed": removed,
        "skipped": skipped,
        "cleanup_reason": (
            "Only delete legacy smoke files in external/godot-master/bin when they match "
            "known smoke markers or the exact pre-marker main.tscn fingerprint."
        ),
    }


def matched_markers(output: str) -> list[str]:
    markers = []
    for marker in (
        SCENE_READY_MARKER,
        SCENE_QUIT_MARKER,
        READY_MARKER,
        MISSING_DLL_MARKER,
        SESSION_UNAVAILABLE_MARKER,
    ):
        if marker in output:
            markers.append(marker)
    return markers


def build_case_command() -> list[str]:
    return [
        str(GODOT_CONSOLE_EXE),
        "--path",
        str(PROJECT_DIR),
        "--rendering-driver",
        REQUESTED_RENDERER,
        "--rendering-method",
        REQUESTED_RENDERING_METHOD,
        "--verbose",
    ]


def excerpt(text: str, limit: int = 2000) -> str:
    if len(text) <= limit:
        return text
    return text[:limit] + "\n...(truncated)..."


def detect_present_skip_reason(output: str, exit_code: int | None) -> str | None:
    if SESSION_UNAVAILABLE_MARKER in output:
        return "Bridge reported session unavailable; D3D12 session creation did not succeed in this environment."
    lower_output = output.lower()
    if any(hint.lower() in lower_output for hint in SKIP_HINTS):
        return (
            "No session-ready marker was produced; console output indicates a D3D12/device/runtime limitation."
        )
    if exit_code == 0 and SCENE_READY_MARKER in output:
        return (
            "Godot project launched and exited cleanly, but no bridge session-ready marker was observed."
        )
    return None


def run_case(case_name: str, dll_path: pathlib.Path) -> dict[str, object]:
    write_project(dll_path)
    command = build_case_command()
    log_path = LOG_DIR / f"{case_name}.log"
    case: dict[str, object] = {
        "dll_path": str(dll_path),
        "dll_exists": dll_path.exists(),
        "command": subprocess.list2cmdline(command),
        "cwd": str(PROJECT_DIR),
        "exit_code": None,
        "status": "fail",
        "timeout": False,
        "matched_markers": [],
        "unexpected_markers": [],
        "log_path": str(log_path),
        "log_excerpt": "",
        "skip_reason": None,
    }

    try:
        proc = subprocess.run(
            command,
            cwd=PROJECT_DIR,
            text=True,
            capture_output=True,
            check=False,
            timeout=TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired as exc:
        output = combined_output(
            subprocess.CompletedProcess(
                exc.cmd,
                returncode=-1,
                stdout=exc.stdout if isinstance(exc.stdout, str) else "",
                stderr=exc.stderr if isinstance(exc.stderr, str) else "",
            )
        )
        log_path.write_text(output + ("\n" if output else ""), encoding="utf-8")
        case["timeout"] = True
        case["log_excerpt"] = excerpt(output)
        return case

    output = combined_output(proc)
    log_path.write_text(output + ("\n" if output else ""), encoding="utf-8")
    case["exit_code"] = proc.returncode
    case["matched_markers"] = matched_markers(output)
    case["log_excerpt"] = excerpt(output)

    if case_name == "missing_dll":
        unexpected_markers = []
        if READY_MARKER in output:
            unexpected_markers.append(READY_MARKER)
        case["unexpected_markers"] = unexpected_markers
        if unexpected_markers:
            case["status"] = "fail"
        elif proc.returncode == 0 and MISSING_DLL_MARKER in output:
            case["status"] = "pass"
        else:
            case["status"] = "fail"
        return case

    if not dll_path.exists():
        case["status"] = "blocked"
        case["skip_reason"] = "Present DLL is missing; missing-DLL fallback case still ran."
        return case

    if READY_MARKER in output:
        case["status"] = "pass"
        return case

    skip_reason = detect_present_skip_reason(output, proc.returncode)
    if skip_reason is not None:
        case["status"] = "skip"
        case["skip_reason"] = skip_reason
        return case

    case["status"] = "fail"
    return case


def write_summary(summary: dict[str, object]) -> None:
    SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
    SUMMARY_PATH.write_text(
        json.dumps(summary, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    cleanup_result = cleanup_legacy_runtime_files()
    summary: dict[str, object] = {
        "status": "fail",
        "project_dir": str(PROJECT_DIR),
        "working_dir": str(PROJECT_DIR),
        "godot_console_exe": str(GODOT_CONSOLE_EXE),
        "requested_renderer": REQUESTED_RENDERER,
        "requested_rendering_method": REQUESTED_RENDERING_METHOD,
        "legacy_runtime_files_removed": cleanup_result["removed"],
        "legacy_runtime_files_skipped": cleanup_result["skipped"],
        "legacy_runtime_cleanup_reason": cleanup_result["cleanup_reason"],
        "cases": {},
    }

    if not GODOT_CONSOLE_EXE.exists():
        summary["status"] = "blocked"
        summary["reason"] = "Missing Godot console executable required for GRX-003."
        write_summary(summary)
        print(json.dumps(summary, indent=2, ensure_ascii=True))
        return 1

    present_case = run_case("present_dll", PRESENT_DLL)
    missing_case = run_case("missing_dll", MISSING_DLL)
    summary["cases"] = {
        "present_dll": present_case,
        "missing_dll": missing_case,
    }

    present_status = str(present_case.get("status"))
    missing_status = str(missing_case.get("status"))
    if missing_status == "pass" and present_status in {"pass", "skip", "blocked"}:
        summary["status"] = "success"
    else:
        summary["status"] = "fail"

    write_summary(summary)
    print(json.dumps(summary, indent=2, ensure_ascii=True))
    return 0 if summary["status"] == "success" else 1


if __name__ == "__main__":
    raise SystemExit(main())
